# Generated by Django 3.2.7 on 2021-10-10 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, default='', upload_to='post_images'),
            preserve_default=False,
        ),
    ]
