# Generated by Django 3.2.7 on 2021-10-10 23:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_alter_post_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='parent',
            field=models.OneToOneField(blank=True, default=-1, on_delete=django.db.models.deletion.DO_NOTHING, to='posts.post'),
            preserve_default=False,
        ),
    ]
